language: java
before_install:
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
- cd vlingo-common && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}/..
- git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
- cd vlingo-actors && mvn install -DskipTests=true
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn install
deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: vaughnvernon
  on:
    branch: master
  passphrase:
    secure: u8XZYz+UT7/liap8I3w8RH59plOmd6UTTRjH9Jkbg7c+c1hQgd+jMdXgB094ygqd+mIVoworPp9cjPdTOghLYg2GDSFpyTg/Ht8IFix41zdp7lhq7nDDLkJmRClrZPqw78Lya9S/vhXHYKx0TfdbxlyW2Q1V7sLu3/tremfYM7PslD3rMTTg8B6syW3NQIrnmXbvCIb1nqDGM4iz26H3iqdiqdr/v6faQK6U4X818Lk4ABTtjmrCLOX2sNdFDiyPdtns9pkU8UnlaaS2E1O0cv9vwk8jaF6UskjlBbhVNNeCvVzOvtM7SbOsHtEFS334v4b9IFe3no/ZVnz7nyZLJ2scKuptuM3umTggs5nrc5jkf4N1CtF4lmB8dmakjhRQvvRCUvQWDGMB2eECh82F1VhS0B2s0OYcKEt2Io3UsDGCsgDCgxDyMI8xA2veRMEvoK4LzrY2LSFYl2iH/7IBA5oJbw5cOeebBRyOlxdPdwP+otGpZOdBVf/IDMlr3zsD/hmEI7l1s92Prqk09Og8fwobLEpEoYcuv6u7It1joEw6YBeMxQHYqP/Rny+vYJw0PnUrYx9YxMHz5zaFE9+hcckIzx8Azt4OKJmLcTEjruWO4f5Koef9bgMx5wP/tWdDkWzGYEbllF6QDjFsrYppRVapFKlyNhlhQ7+Rs0h7Ruw=
  key:
    secure: ueowihkewwiCI42y5vNuO/oNhfISjvuMElL80VwZN37/ltHYHGbX+1o8o3mhZWSQbCqpSlShEG1q/B/P8R1JeNbgmbj3bPxnrw32HFezppJiXvkvQ8r7LXOkVuyMte+0G91GNzzD/MXlh+Bt49cBqk+lJowZONw3cGW02RI1Q72oMAZ/AuhZmR8NoD6WlM2tO4ClSyrU7MsPOgiHV4TyqJ+U3oz2CUJTZrHKlH6hHG9pZqEs3X+WQDAzs4S8AJzQSGDPhO2lAOEOdFmyfcU10tjX4DUk0AjcPFuQ2j6me9RdAfsjLkVUkZ6DEJXdLmADfpI9QFDUJcBJkKhsHglnR/1yj7vMNdaxGrYhWs5WZ4K5k8X0gaGXORJRyUW9RnQIv/ifwAyrJOPvJiLFKi1SbZEszvw4so/ht+nWmXas/HHpIQqIwJWz/wPfKN03IOERcZjR/vtWPY2Z4E2jRZxaQuLeRKAeiPIpIQwdR0FDH7HtVekSoV8yWft3AwO6lp+D9Kx/TOyHXkRIrmAROkK9evk5I+lFqHdzdY3cXwzwwDFQ3x1aZeVgvs1nJAcAqgaQDoTRuwPxF2OW35tf96vZFqcrEVFAGdc3uXYEVLviC0zC98Wzf/DbAJ9un1IETFgMhISolAUgCwTXFy7pZIYWORzHBSd7YxdZN34U4tOgAXE=
