postgres:
  # use this disposable Postgres instance to not have to install it locally
  # $> docker-compose up -d
  image: "postgres:latest"
  ports:
    - '5432:5432'
  environment:
    # create the DB after the service is up with:
    # $> docker-compose exec postgres psql -c "CREATE DATABASE vlingo_test;" -U postgres
    POSTGRES_PASSWORD: vlingo123
    POSTGRES_USER: vlingo_test
